"""empty message

Revision ID: 02bc2d4fbef7
Revises: ff0ad1ddd6fe
Create Date: 2019-03-19 17:11:42.167156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bc2d4fbef7'
down_revision = 'ff0ad1ddd6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_credentials_token'), 'user_credentials', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_credentials_token'), table_name='user_credentials')
    # ### end Alembic commands ###
