"""empty message

Revision ID: 711ba7c86d9e
Revises: b5750dd5e211
Create Date: 2019-03-18 03:01:58.657846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711ba7c86d9e'
down_revision = 'b5750dd5e211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=True),
    sa.Column('token_uri', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('scopes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('user', sa.Column('google_oauth_state', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_oauth_state')
    op.drop_table('user_credentials')
    # ### end Alembic commands ###
