"""empty message

Revision ID: ff0ad1ddd6fe
Revises: 711ba7c86d9e
Create Date: 2019-03-18 04:28:14.079683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0ad1ddd6fe'
down_revision = '711ba7c86d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('picture_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_url')
    op.drop_column('user', 'name')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
