services:
  # Background worker for processing jobs
  worker: &worker
    build: ./server
    volumes:
      - ./server:/app/
      - model_data:/var/lib/model_data/
    command: supervisord -n -c /etc/supervisord/supervisord-worker.conf
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres_db:5432/${DATABASE_NAME}
      - APP_URL=${APP_URL}
      - API_URL=${API_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MSFT_APP_ID=${MSFT_APP_ID}
      - MSFT_APP_SECRET=${MSFT_APP_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - REDIS_URL=${REDIS_URL}
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  # FastAPI / Starlette
  api:
    <<: *worker
    command: supervisord -n -c /etc/supervisord/supervisord.conf
    ports:
      - 8888:8080

  # Redis for job queue.
  redis:
    image: redis:5.0.5-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    environment:
      - REDIS_PORT=6379

  # PostgreSQL database
  postgres_db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '7432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

  # Log Aggregation.
  promtail:
    image: grafana/promtail:1.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/docker-config.yaml

  loki:
    image: grafana/loki:2.3.0
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:master
    ports:
      - '3300:3000'
    depends_on:
      - loki

volumes:
  postgres-data: # PostgreSQL data volume
  model_data:
  redis-data:
