version: '3'

services:
  # FastAPI / Starlette
  api:
    build: ./server
    ports:
      - 8888:8080
    volumes:
      - ./server:/app/
      - model_data:/var/lib/model_data/
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres_db:5432/${DATABASE_NAME}
      - APP_URL=${APP_URL}
      - API_URL=${API_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - MSFT_APP_ID=${MSFT_APP_ID}
      - MSFT_APP_SECRET=${MSFT_APP_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}

  # PostgreSQL database
  postgres_db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '7432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

  # PostgreSQL database (Testing)
  postgres_test:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
  model_data:
