services:
  # Background worker for processing jobs
  worker: &worker
    build: .
    command: supervisord -n -c /etc/supervisord/supervisord-worker.conf
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres_db:5432/${DATABASE_NAME}
    env_file:
      - .env

  # FastAPI / Starlette
  api:
    <<: *worker
    command: /var/scripts/entrypoint.sh
    ports:
      - 80:80

  # Redis for job queue.
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    environment:
      - REDIS_PORT=6379

  # PostgreSQL database
  postgres_db:
    image: postgres:16.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

volumes:
  postgres_data: # PostgreSQL data volume
  redis-data:
