version: '2'

services:
  # Sanic Web Server
  api:
    build: ./app
    ports:
      - 5555:80
    links:
      - postgres:postgres
    depends_on:
      - postgres
    volumes:
      - ./app:/app/
      - model_data:/var/lib/model_data/
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres:5432/${DATABASE_NAME}
      - FLASK_APP=api:app

  # PostgreSQL database
  postgres:
    image: sameersbn/postgresql:9.6-2
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "6432:5432"
    environment:
      DB_USER: ${DATABASE_USER}
      DB_PASS: ${DATABASE_PASS}
      DB_NAME: ${DATABASE_NAME}

volumes:
  postgres_data:   # PostgreSQL data volume
  model_data:
