version: '3'

services:
  # Background worker for processing jobs
  worker: &worker
    build: ./server
    volumes:
      - ./server:/app/
      - model_data:/var/lib/model_data/
    command: /var/scripts/entrypoint-worker.sh
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASS}@postgres_db:5432/${DATABASE_NAME}
      - LOG_LEVEL=debug
    env_file:
      - .env

  # FastAPI / Starlette
  api:
    <<: *worker
    command: /var/scripts/entrypoint-dev.sh
    ports:
      - 8888:8080

  # Redis for job queue.
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    environment:
      - REDIS_PORT=6379

  # PostgreSQL database
  postgres_db:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '7432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}

  # PostgreSQL database (Testing)
  postgres_test:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
  redis-data:
  model_data:
