"""empty message

Revision ID: 0515e5f83a1a
Revises: 865a5e9e65c0
Create Date: 2018-11-05 01:35:13.829477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0515e5f83a1a'
down_revision = '865a5e9e65c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_title'), table_name='event')
    # ### end Alembic commands ###
