[tool.poetry]
name = "app"
version = "0.1.0"
description = "Timecouncil API"
authors = ["winxton <winxton@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.68.1"
SQLAlchemy = "^1.4.23"
alembic = "^1.7"
requests = "^2.25.1"
psycopg2-binary = "^2.9.1"
shortuuid = "^1.0.1"
google-api-python-client = "^1.12.8"
uvicorn ="^0.13.4"
oauthlib = "^3.1.0"
google-auth = "^1.28.0"
requests-oauthlib = "^1.3.0"
google-auth-oauthlib = "^0.4.3"
PyJWT = "^2.0.1"
asyncpg = "^0.24.0"
orjson = "=3.5.1"
gunicorn = "^20.0.4"
uvloop = "^0.15.2"
httptools = "^0.1.1"
python-dateutil = "^2.8.2"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
mypy = "^0.812"
black = "^20.8b1"
pytest-asyncio = "^0.14.0"
httpx = "^0.16.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
create = true
in-project = true

[tool.poetry.scripts]
start = "app.main:start"
