"""add event creator

Revision ID: 1c663de078eb
Revises: 2beaa41d8d45
Create Date: 2022-06-02 19:29:58.595709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c663de078eb'
down_revision = '2beaa41d8d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('creator_id', sa.String(length=255), nullable=True))
    op.create_foreign_key('event_creator_fk', 'event', 'event_participant', ['creator_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_creator_fk', 'event', type_='foreignkey')
    op.drop_column('event', 'creator_id')
    # ### end Alembic commands ###
