"""add user timezone

Revision ID: 1f814424ccd9
Revises: da81e6992f20
Create Date: 2021-01-25 17:37:27.903018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f814424ccd9'
down_revision = 'da81e6992f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'calendar', ['id'])
    op.add_column('user', sa.Column('timezone', sa.String(length=255), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timezone')
    op.drop_constraint(None, 'calendar', type_='unique')
    # ### end Alembic commands ###
