"""add email to calendar

Revision ID: 2beaa41d8d45
Revises: d79eac5a965c
Create Date: 2022-05-30 09:53:11.269088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2beaa41d8d45'
down_revision = 'd79eac5a965c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('email_', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'email_')
    # ### end Alembic commands ###
