"""participant email could be null

Revision ID: 402c7709a1c2
Revises: fd00debde2df
Create Date: 2021-11-17 16:01:48.647931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402c7709a1c2'
down_revision = 'fd00debde2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_participant', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_participant', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
