"""add sync token

Revision ID: 5d1096f771a9
Revises: bdec7408a5e9
Create Date: 2020-07-19 11:48:00.156157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1096f771a9'
down_revision = 'bdec7408a5e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('sync_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar', 'sync_token')
    # ### end Alembic commands ###
