"""store json for token

Revision ID: 654617b9b8da
Revises: c85ac05cee03
Create Date: 2020-10-11 03:31:01.437969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '654617b9b8da'
down_revision = 'c85ac05cee03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('label', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('user_credentials', sa.Column('token_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_index('ix_user_credentials_token', table_name='user_credentials')
    op.drop_column('user_credentials', 'expires_at')
    op.drop_column('user_credentials', 'refresh_token')
    op.drop_column('user_credentials', 'token_uri')
    op.drop_column('user_credentials', 'client_id')
    op.drop_column('user_credentials', 'token')
    op.drop_column('user_credentials', 'client_secret')
    op.drop_column('user_credentials', 'scopes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('scopes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_credentials', sa.Column('client_secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_credentials', sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_credentials', sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_credentials', sa.Column('token_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_credentials', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_credentials', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_user_credentials_token', 'user_credentials', ['token'], unique=False)
    op.drop_column('user_credentials', 'token_data')
    op.alter_column('label', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
