"""Rename participant email field

Revision ID: 74c320e8df6d
Revises: 402c7709a1c2
Create Date: 2021-11-18 12:35:07.438243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c320e8df6d'
down_revision = '402c7709a1c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participant', sa.Column('email_', sa.String(length=255), nullable=True))
    op.drop_index('ix_event_participant_email', table_name='event_participant')
    op.create_index(op.f('ix_event_participant_email_'), 'event_participant', ['email_'], unique=False)
    op.drop_column('event_participant', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_participant', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_event_participant_email_'), table_name='event_participant')
    op.create_index('ix_event_participant_email', 'event_participant', ['email'], unique=False)
    op.drop_column('event_participant', 'email_')
    # ### end Alembic commands ###
