"""add google id

Revision ID: 88f2eeaf8eba
Revises: 1f814424ccd9
Create Date: 2021-02-02 06:20:54.860417

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '88f2eeaf8eba'
down_revision = '1f814424ccd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('unique_google_id', 'calendar', ['google_id'])
    op.execute(
        """
        UPDATE calendar
        SET google_id = id"""
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_google_id', 'calendar', type_='unique')
    op.drop_column('calendar', 'google_id')
    # ### end Alembic commands ###
