"""event calendar cascade

Revision ID: 94ee8e0c03a1
Revises: a38f7f332e15
Create Date: 2021-03-11 12:54:05.004083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ee8e0c03a1'
down_revision = 'a38f7f332e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_calendar_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(
        'event_calendar_id_fkey', 'event', 'calendar', ['calendar_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_calendar_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key('event_calendar_id_fkey', 'event', 'calendar', ['calendar_id'], ['id'])
    # ### end Alembic commands ###
