"""add photo to contact

Revision ID: a2403567356e
Revises: 82a1c8b0e171
Create Date: 2021-11-16 12:44:17.952083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2403567356e'
down_revision = '82a1c8b0e171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'photo_url')
    # ### end Alembic commands ###
