"""add original start to event

Revision ID: a8a0765e061d
Revises: c0d1a3c14c2c
Create Date: 2020-12-09 01:21:17.822504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a0765e061d'
down_revision = 'c0d1a3c14c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('original_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event', sa.Column('original_start_day', sa.String(length=10), nullable=True))
    op.add_column('event', sa.Column('original_timezone', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'original_timezone')
    op.drop_column('event', 'original_start_day')
    op.drop_column('event', 'original_start')
    # ### end Alembic commands ###
