"""add position

Revision ID: b1a4af9c084c
Revises: c5903796a10d
Create Date: 2020-07-27 22:14:40.721983

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b1a4af9c084c'
down_revision = 'c5903796a10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'position')
    # ### end Alembic commands ###
