"""empty message

Revision ID: c57fa0316e1b
Revises: 7094228b44fd
Create Date: 2019-12-15 21:42:31.458415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c57fa0316e1b'
down_revision = '7094228b44fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_label_key'), 'label', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_key'), table_name='label')
    # ### end Alembic commands ###
