"""Add participant model

Revision ID: ca93c78c26f2
Revises: a2403567356e
Create Date: 2021-11-16 16:10:24.195910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca93c78c26f2'
down_revision = 'a2403567356e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'event_participant',
        sa.Column('id', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('event_id', sa.String(length=255), nullable=False),
        sa.Column('contact_id', sa.String(length=255), nullable=True),
        sa.Column('response_status', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ['contact_id'],
            ['contact.id'],
        ),
        sa.ForeignKeyConstraint(
            ['event_id'],
            ['event.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_event_participant_email'), 'event_participant', ['email'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_participant_email'), table_name='event_participant')
    op.drop_table('event_participant')
    # ### end Alembic commands ###
