"""add index to recurring event

Revision ID: d4fdf3d510c8
Revises: 88f2eeaf8eba
Create Date: 2021-02-26 21:07:03.626333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4fdf3d510c8'
down_revision = '88f2eeaf8eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_recurring_event_id'), 'event', ['recurring_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_recurring_event_id'), table_name='event')
    # ### end Alembic commands ###
