"""init

Revision ID: da81e6992f20
Revises: 
Create Date: 2021-01-13 05:16:46.945325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da81e6992f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=255), nullable=True),
    sa.Column('google_oauth_state', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('background_color', sa.String(length=10), nullable=True),
    sa.Column('foreground_color', sa.String(length=10), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('access_role', sa.String(length=50), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('sync_token', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('label',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('color_hex', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_label_key'), 'label', ['key'], unique=False)
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', postgresql.ENUM('google', 'microsoft', name='providertype'), nullable=False),
    sa.Column('token_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider')
    )
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('g_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_day', sa.String(length=10), nullable=True),
    sa.Column('end_day', sa.String(length=10), nullable=True),
    sa.Column('time_zone', sa.String(length=255), nullable=True),
    sa.Column('recurrences', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('recurring_event_id', sa.String(), nullable=True),
    sa.Column('original_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_start_day', sa.String(length=10), nullable=True),
    sa.Column('original_timezone', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.ForeignKeyConstraint(['recurring_event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('g_id')
    )
    op.create_index(op.f('ix_event_title'), 'event', ['title'], unique=False)
    op.create_table('label_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('resource_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_label',
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_label')
    op.drop_table('webhook')
    op.drop_table('label_rule')
    op.drop_index(op.f('ix_event_title'), table_name='event')
    op.drop_table('event')
    op.drop_table('user_credentials')
    op.drop_index(op.f('ix_label_key'), table_name='label')
    op.drop_table('label')
    op.drop_table('calendar')
    op.drop_table('user')
    # ### end Alembic commands ###
