"""add full dates

Revision ID: eb8a9fb3e518
Revises: 654617b9b8da
Create Date: 2020-10-29 12:38:12.692719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb8a9fb3e518'
down_revision = '654617b9b8da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_day', sa.String(length=10), nullable=True))
    op.add_column('event', sa.Column('start_day', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'start_day')
    op.drop_column('event', 'end_day')
    # ### end Alembic commands ###
