"""Add email field with index

Revision ID: fd00debde2df
Revises: ca93c78c26f2
Create Date: 2021-11-17 10:38:38.880485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd00debde2df'
down_revision = 'ca93c78c26f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.drop_column('contact', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_column('contact', 'email')
    # ### end Alembic commands ###
