"""add parent to label

Revision ID: ff74609313e9
Revises: c57fa0316e1b
Create Date: 2020-04-13 00:22:38.278472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff74609313e9'
down_revision = 'c57fa0316e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('parent_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'label', 'label', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'label', type_='foreignkey')
    op.drop_column('label', 'parent_id')
    # ### end Alembic commands ###
